spring:
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/email?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thtjdalstest@gmail.com
    password: w s h t v q q e c q v q n j p n
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
