spring:
  application:
    name:
  datasource:
    url: jdbc:mysql://localhost:3306/nodagi_email?serverTimezone=Asia/Seoul
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: none

  kafka:
    bootstrap-servers: 192.168.0.20:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      group-id: email-group
      auto-offset-reset: earliest

#  redis:
#    host: localhost
#    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: thtjdalstest@gmail.com
    password: w s h t v q q e c q v q n j p n
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
